// Generated by https://github.com/xhaoh94/PbTool
// DO NOT EDIT!
package pb

const (
	CMD_Bcst_EnterMap uint32 = 500200001
	CMD_Bcst_LeaveMap uint32 = 500200002
	CMD_Bcst_Move uint32 = 500200003
	CMD_Interior_EnterVision uint32 = 99900001
	CMD_Interior_LeaveVision uint32 = 99900002
	CMD_Interior_Move uint32 = 99900003
)