// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/common.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Entity struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Position             *Vector3 `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Spaceid              string   `protobuf:"bytes,4,opt,name=spaceid,proto3" json:"spaceid,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Etype                int32    `protobuf:"varint,6,opt,name=etype,proto3" json:"etype,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entity) Reset()         { *m = Entity{} }
func (m *Entity) String() string { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()    {}
func (*Entity) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{0}
}

func (m *Entity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entity.Unmarshal(m, b)
}
func (m *Entity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entity.Marshal(b, m, deterministic)
}
func (m *Entity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entity.Merge(m, src)
}
func (m *Entity) XXX_Size() int {
	return xxx_messageInfo_Entity.Size(m)
}
func (m *Entity) XXX_DiscardUnknown() {
	xxx_messageInfo_Entity.DiscardUnknown(m)
}

var xxx_messageInfo_Entity proto.InternalMessageInfo

func (m *Entity) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Entity) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Entity) GetPosition() *Vector3 {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Entity) GetSpaceid() string {
	if m != nil {
		return m.Spaceid
	}
	return ""
}

func (m *Entity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Entity) GetEtype() int32 {
	if m != nil {
		return m.Etype
	}
	return 0
}

type Vector3 struct {
	X                    float32  `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z                    float32  `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vector3) Reset()         { *m = Vector3{} }
func (m *Vector3) String() string { return proto.CompactTextString(m) }
func (*Vector3) ProtoMessage()    {}
func (*Vector3) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{1}
}

func (m *Vector3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vector3.Unmarshal(m, b)
}
func (m *Vector3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vector3.Marshal(b, m, deterministic)
}
func (m *Vector3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vector3.Merge(m, src)
}
func (m *Vector3) XXX_Size() int {
	return xxx_messageInfo_Vector3.Size(m)
}
func (m *Vector3) XXX_DiscardUnknown() {
	xxx_messageInfo_Vector3.DiscardUnknown(m)
}

var xxx_messageInfo_Vector3 proto.InternalMessageInfo

func (m *Vector3) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Vector3) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Vector3) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

func init() {
	proto.RegisterType((*Entity)(nil), "Entity")
	proto.RegisterType((*Vector3)(nil), "Vector3")
}

func init() { proto.RegisterFile("common/common.proto", fileDescriptor_8f954d82c0b891f6) }

var fileDescriptor_8f954d82c0b891f6 = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8f, 0x3f, 0x4e, 0xc5, 0x30,
	0x0c, 0x87, 0x65, 0xd3, 0xf6, 0x3d, 0xfc, 0x10, 0x43, 0x60, 0xc8, 0x58, 0x55, 0x0c, 0x9d, 0x8a,
	0x44, 0x47, 0x36, 0x24, 0x2e, 0x90, 0x81, 0x81, 0xad, 0x7f, 0x32, 0x64, 0x68, 0x1c, 0xb5, 0x91,
	0x68, 0x7a, 0x12, 0xce, 0xc0, 0x29, 0x51, 0x5d, 0x78, 0x53, 0xf2, 0xfd, 0x2c, 0xdb, 0x9f, 0xe9,
	0x61, 0xe0, 0x69, 0x62, 0xff, 0x7c, 0x3c, 0x4d, 0x98, 0x39, 0x72, 0xf5, 0x0d, 0x54, 0xbc, 0xfb,
	0xe8, 0x62, 0x52, 0xf7, 0x84, 0x6e, 0xd4, 0x50, 0x42, 0x7d, 0x6b, 0xd0, 0x8d, 0xea, 0x91, 0x72,
	0xfe, 0xf2, 0x76, 0xd6, 0x28, 0xd1, 0x01, 0xea, 0x89, 0xce, 0x81, 0x17, 0x17, 0x1d, 0x7b, 0x7d,
	0x53, 0x42, 0x7d, 0x79, 0x39, 0x37, 0x1f, 0x76, 0x88, 0x3c, 0xb7, 0xe6, 0x5a, 0x51, 0x9a, 0x4e,
	0x4b, 0xe8, 0x06, 0xeb, 0x46, 0x9d, 0x49, 0xf7, 0x3f, 0x2a, 0x45, 0x99, 0xef, 0x26, 0xab, 0x73,
	0x89, 0xe5, 0xbf, 0x6f, 0xb2, 0x31, 0x05, 0xab, 0x8b, 0x12, 0xea, 0xdc, 0x1c, 0x50, 0xb5, 0x74,
	0xfa, 0x1b, 0xac, 0xee, 0x08, 0x56, 0x31, 0x43, 0x03, 0xeb, 0x4e, 0x49, 0xa4, 0xd0, 0x40, 0xda,
	0x69, 0x13, 0x13, 0x34, 0xb0, 0xbd, 0x5d, 0x3e, 0xb3, 0xe6, 0x35, 0xf4, 0x3f, 0x88, 0xa1, 0xef,
	0x0b, 0xb9, 0xb1, 0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x63, 0x85, 0x59, 0xd5, 0xfa, 0x00, 0x00,
	0x00,
}
