// Code generated by protoc-gen-go. DO NOT EDIT.
// source: interior/map/interior_entermap.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//bcst=99900001
type Interior_EnterVision struct {
	Roles                []uint32 `protobuf:"varint,1,rep,packed,name=roles,proto3" json:"roles,omitempty"`
	Role                 *Entity  `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Interior_EnterVision) Reset()         { *m = Interior_EnterVision{} }
func (m *Interior_EnterVision) String() string { return proto.CompactTextString(m) }
func (*Interior_EnterVision) ProtoMessage()    {}
func (*Interior_EnterVision) Descriptor() ([]byte, []int) {
	return fileDescriptor_220a3f276af122ca, []int{0}
}

func (m *Interior_EnterVision) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interior_EnterVision.Unmarshal(m, b)
}
func (m *Interior_EnterVision) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interior_EnterVision.Marshal(b, m, deterministic)
}
func (m *Interior_EnterVision) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interior_EnterVision.Merge(m, src)
}
func (m *Interior_EnterVision) XXX_Size() int {
	return xxx_messageInfo_Interior_EnterVision.Size(m)
}
func (m *Interior_EnterVision) XXX_DiscardUnknown() {
	xxx_messageInfo_Interior_EnterVision.DiscardUnknown(m)
}

var xxx_messageInfo_Interior_EnterVision proto.InternalMessageInfo

func (m *Interior_EnterVision) GetRoles() []uint32 {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *Interior_EnterVision) GetRole() *Entity {
	if m != nil {
		return m.Role
	}
	return nil
}

//bcst=99900002
type Interior_LeaveVision struct {
	Roles                []uint32 `protobuf:"varint,1,rep,packed,name=roles,proto3" json:"roles,omitempty"`
	RoleId               uint32   `protobuf:"varint,2,opt,name=roleId,proto3" json:"roleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Interior_LeaveVision) Reset()         { *m = Interior_LeaveVision{} }
func (m *Interior_LeaveVision) String() string { return proto.CompactTextString(m) }
func (*Interior_LeaveVision) ProtoMessage()    {}
func (*Interior_LeaveVision) Descriptor() ([]byte, []int) {
	return fileDescriptor_220a3f276af122ca, []int{1}
}

func (m *Interior_LeaveVision) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interior_LeaveVision.Unmarshal(m, b)
}
func (m *Interior_LeaveVision) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interior_LeaveVision.Marshal(b, m, deterministic)
}
func (m *Interior_LeaveVision) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interior_LeaveVision.Merge(m, src)
}
func (m *Interior_LeaveVision) XXX_Size() int {
	return xxx_messageInfo_Interior_LeaveVision.Size(m)
}
func (m *Interior_LeaveVision) XXX_DiscardUnknown() {
	xxx_messageInfo_Interior_LeaveVision.DiscardUnknown(m)
}

var xxx_messageInfo_Interior_LeaveVision proto.InternalMessageInfo

func (m *Interior_LeaveVision) GetRoles() []uint32 {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *Interior_LeaveVision) GetRoleId() uint32 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

//bcst=99900003
type Interior_Move struct {
	Roles                []uint32   `protobuf:"varint,1,rep,packed,name=roles,proto3" json:"roles,omitempty"`
	RoleId               uint32     `protobuf:"varint,2,opt,name=roleId,proto3" json:"roleId,omitempty"`
	Points               []*Vector3 `protobuf:"bytes,3,rep,name=points,proto3" json:"points,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Interior_Move) Reset()         { *m = Interior_Move{} }
func (m *Interior_Move) String() string { return proto.CompactTextString(m) }
func (*Interior_Move) ProtoMessage()    {}
func (*Interior_Move) Descriptor() ([]byte, []int) {
	return fileDescriptor_220a3f276af122ca, []int{2}
}

func (m *Interior_Move) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interior_Move.Unmarshal(m, b)
}
func (m *Interior_Move) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interior_Move.Marshal(b, m, deterministic)
}
func (m *Interior_Move) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interior_Move.Merge(m, src)
}
func (m *Interior_Move) XXX_Size() int {
	return xxx_messageInfo_Interior_Move.Size(m)
}
func (m *Interior_Move) XXX_DiscardUnknown() {
	xxx_messageInfo_Interior_Move.DiscardUnknown(m)
}

var xxx_messageInfo_Interior_Move proto.InternalMessageInfo

func (m *Interior_Move) GetRoles() []uint32 {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *Interior_Move) GetRoleId() uint32 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *Interior_Move) GetPoints() []*Vector3 {
	if m != nil {
		return m.Points
	}
	return nil
}

func init() {
	proto.RegisterType((*Interior_EnterVision)(nil), "Interior_EnterVision")
	proto.RegisterType((*Interior_LeaveVision)(nil), "Interior_LeaveVision")
	proto.RegisterType((*Interior_Move)(nil), "Interior_Move")
}

func init() {
	proto.RegisterFile("interior/map/interior_entermap.proto", fileDescriptor_220a3f276af122ca)
}

var fileDescriptor_220a3f276af122ca = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xc9, 0xcc, 0x2b, 0x49,
	0x2d, 0xca, 0xcc, 0x2f, 0xd2, 0xcf, 0x4d, 0x2c, 0xd0, 0x87, 0x71, 0xe2, 0x53, 0x41, 0x8c, 0xdc,
	0xc4, 0x02, 0xbd, 0x82, 0xa2, 0xfc, 0x92, 0x7c, 0x29, 0xe1, 0xe4, 0xfc, 0xdc, 0xdc, 0xfc, 0x3c,
	0x7d, 0x08, 0x05, 0x11, 0x54, 0xf2, 0xe4, 0x12, 0xf1, 0x84, 0xa9, 0x77, 0x05, 0x31, 0xc2, 0x32,
	0x8b, 0x33, 0xf3, 0xf3, 0x84, 0x44, 0xb8, 0x58, 0x8b, 0xf2, 0x73, 0x52, 0x8b, 0x25, 0x18, 0x15,
	0x98, 0x35, 0x78, 0x83, 0x20, 0x1c, 0x21, 0x69, 0x2e, 0x16, 0x10, 0x43, 0x82, 0x49, 0x81, 0x51,
	0x83, 0xdb, 0x88, 0x5d, 0xcf, 0x35, 0xaf, 0x24, 0xb3, 0xa4, 0x32, 0x08, 0x2c, 0xa8, 0xe4, 0x82,
	0x64, 0x94, 0x4f, 0x6a, 0x62, 0x59, 0x2a, 0x5e, 0xa3, 0xc4, 0xb8, 0xd8, 0x40, 0x0c, 0xcf, 0x14,
	0xb0, 0x61, 0xbc, 0x41, 0x50, 0x9e, 0x52, 0x3c, 0x17, 0x2f, 0xdc, 0x14, 0xdf, 0xfc, 0xb2, 0x54,
	0xd2, 0xb4, 0x0b, 0x29, 0x70, 0xb1, 0x15, 0xe4, 0x67, 0xe6, 0x95, 0x14, 0x4b, 0x30, 0x2b, 0x30,
	0x6b, 0x70, 0x1b, 0x71, 0xe8, 0x85, 0xa5, 0x26, 0x97, 0xe4, 0x17, 0x19, 0x07, 0x41, 0xc5, 0x9d,
	0xb8, 0xa3, 0x58, 0xf4, 0xac, 0x0b, 0x92, 0x56, 0x31, 0x31, 0x05, 0x24, 0x25, 0xb1, 0x81, 0x43,
	0xc1, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x97, 0x28, 0x72, 0x9f, 0x42, 0x01, 0x00, 0x00,
}
