// // Code generated by protoc-gen-go. DO NOT EDIT.
// // source: test/test.proto

package pb

// import (
// 	fmt "fmt"
// 	proto "github.com/golang/protobuf/proto"
// 	math "math"
// )

// // Reference imports to suppress errors if they are not otherwise used.
// var _ = proto.Marshal
// var _ = fmt.Errorf
// var _ = math.Inf

// // This is a compile-time assertion to ensure that this generated file
// // is compatible with the proto package it is being compiled against.
// // A compilation error at this line likely means your copy of the
// // proto package needs to be updated.
// const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// type A struct {
// 	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
// 	Position             *Vector3 `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
// 	Etype                int32    `protobuf:"varint,3,opt,name=etype,proto3" json:"etype,omitempty"`
// 	XXX_NoUnkeyedLiteral struct{} `json:"-"`
// 	XXX_unrecognized     []byte   `json:"-"`
// 	XXX_sizecache        int32    `json:"-"`
// }

// func (m *A) Reset()         { *m = A{} }
// func (m *A) String() string { return proto.CompactTextString(m) }
// func (*A) ProtoMessage()    {}
// func (*A) Descriptor() ([]byte, []int) {
// 	return fileDescriptor_84eb23d74a64bdab, []int{0}
// }

// func (m *A) XXX_Unmarshal(b []byte) error {
// 	return xxx_messageInfo_A.Unmarshal(m, b)
// }
// func (m *A) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
// 	return xxx_messageInfo_A.Marshal(b, m, deterministic)
// }
// func (m *A) XXX_Merge(src proto.Message) {
// 	xxx_messageInfo_A.Merge(m, src)
// }
// func (m *A) XXX_Size() int {
// 	return xxx_messageInfo_A.Size(m)
// }
// func (m *A) XXX_DiscardUnknown() {
// 	xxx_messageInfo_A.DiscardUnknown(m)
// }

// var xxx_messageInfo_A proto.InternalMessageInfo

// func (m *A) GetId() string {
// 	if m != nil {
// 		return m.Id
// 	}
// 	return ""
// }

// func (m *A) GetPosition() *Vector3 {
// 	if m != nil {
// 		return m.Position
// 	}
// 	return nil
// }

// func (m *A) GetEtype() int32 {
// 	if m != nil {
// 		return m.Etype
// 	}
// 	return 0
// }

// type B struct {
// 	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
// 	Position             *Vector3 `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
// 	Etype                int32    `protobuf:"varint,3,opt,name=etype,proto3" json:"etype,omitempty"`
// 	XXX_NoUnkeyedLiteral struct{} `json:"-"`
// 	XXX_unrecognized     []byte   `json:"-"`
// 	XXX_sizecache        int32    `json:"-"`
// }

// func (m *B) Reset()         { *m = B{} }
// func (m *B) String() string { return proto.CompactTextString(m) }
// func (*B) ProtoMessage()    {}
// func (*B) Descriptor() ([]byte, []int) {
// 	return fileDescriptor_84eb23d74a64bdab, []int{1}
// }

// func (m *B) XXX_Unmarshal(b []byte) error {
// 	return xxx_messageInfo_B.Unmarshal(m, b)
// }
// func (m *B) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
// 	return xxx_messageInfo_B.Marshal(b, m, deterministic)
// }
// func (m *B) XXX_Merge(src proto.Message) {
// 	xxx_messageInfo_B.Merge(m, src)
// }
// func (m *B) XXX_Size() int {
// 	return xxx_messageInfo_B.Size(m)
// }
// func (m *B) XXX_DiscardUnknown() {
// 	xxx_messageInfo_B.DiscardUnknown(m)
// }

// var xxx_messageInfo_B proto.InternalMessageInfo

// func (m *B) GetId() string {
// 	if m != nil {
// 		return m.Id
// 	}
// 	return ""
// }

// func (m *B) GetPosition() *Vector3 {
// 	if m != nil {
// 		return m.Position
// 	}
// 	return nil
// }

// func (m *B) GetEtype() int32 {
// 	if m != nil {
// 		return m.Etype
// 	}
// 	return 0
// }

// type Vector3 struct {
// 	X                    float32  `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
// 	Y                    float32  `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
// 	Z                    float32  `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
// 	XXX_NoUnkeyedLiteral struct{} `json:"-"`
// 	XXX_unrecognized     []byte   `json:"-"`
// 	XXX_sizecache        int32    `json:"-"`
// }

// func (m *Vector3) Reset()         { *m = Vector3{} }
// func (m *Vector3) String() string { return proto.CompactTextString(m) }
// func (*Vector3) ProtoMessage()    {}
// func (*Vector3) Descriptor() ([]byte, []int) {
// 	return fileDescriptor_84eb23d74a64bdab, []int{2}
// }

// func (m *Vector3) XXX_Unmarshal(b []byte) error {
// 	return xxx_messageInfo_Vector3.Unmarshal(m, b)
// }
// func (m *Vector3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
// 	return xxx_messageInfo_Vector3.Marshal(b, m, deterministic)
// }
// func (m *Vector3) XXX_Merge(src proto.Message) {
// 	xxx_messageInfo_Vector3.Merge(m, src)
// }
// func (m *Vector3) XXX_Size() int {
// 	return xxx_messageInfo_Vector3.Size(m)
// }
// func (m *Vector3) XXX_DiscardUnknown() {
// 	xxx_messageInfo_Vector3.DiscardUnknown(m)
// }

// var xxx_messageInfo_Vector3 proto.InternalMessageInfo

// func (m *Vector3) GetX() float32 {
// 	if m != nil {
// 		return m.X
// 	}
// 	return 0
// }

// func (m *Vector3) GetY() float32 {
// 	if m != nil {
// 		return m.Y
// 	}
// 	return 0
// }

// func (m *Vector3) GetZ() float32 {
// 	if m != nil {
// 		return m.Z
// 	}
// 	return 0
// }

// func init() {
// 	proto.RegisterType((*A)(nil), "A")
// 	proto.RegisterType((*B)(nil), "B")
// 	proto.RegisterType((*Vector3)(nil), "Vector3")
// }

// func init() { proto.RegisterFile("test/test.proto", fileDescriptor_84eb23d74a64bdab) }

// var fileDescriptor_84eb23d74a64bdab = []byte{
// 	// 166 bytes of a gzipped FileDescriptorProto
// 	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x49, 0x2d, 0x2e,
// 	0xd1, 0x07, 0x11, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x4a, 0xfe, 0x5c, 0x8c, 0x8e, 0x42, 0x7c,
// 	0x5c, 0x4c, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x4c, 0x99, 0x29, 0x42, 0x2a,
// 	0x5c, 0x1c, 0x05, 0xf9, 0xc5, 0x99, 0x25, 0x99, 0xf9, 0x79, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xdc,
// 	0x46, 0x1c, 0x7a, 0x61, 0xa9, 0xc9, 0x25, 0xf9, 0x45, 0xc6, 0x41, 0x70, 0x19, 0x21, 0x11, 0x2e,
// 	0xd6, 0xd4, 0x92, 0xca, 0x82, 0x54, 0x09, 0x66, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x08, 0x07, 0x64,
// 	0xa0, 0x13, 0x55, 0x0d, 0x34, 0xe6, 0x62, 0x87, 0x2a, 0x15, 0xe2, 0xe1, 0x62, 0xac, 0x00, 0x9b,
// 	0xca, 0x14, 0xc4, 0x58, 0x01, 0xe2, 0x55, 0x82, 0x4d, 0x63, 0x0a, 0x62, 0xac, 0x04, 0xf1, 0xaa,
// 	0xc0, 0x1a, 0x99, 0x82, 0x18, 0xab, 0x9c, 0xb8, 0xa3, 0x58, 0xf4, 0xac, 0x0b, 0x92, 0x56, 0x31,
// 	0x31, 0x15, 0x24, 0x25, 0xb1, 0x81, 0xbd, 0x6a, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x96, 0xd5,
// 	0xcd, 0x81, 0xfd, 0x00, 0x00, 0x00,
// }
